// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace BookShower.DAL.Entities;

public partial class Books
{
    public int Id { get; set; }

    public string Title { get; set; }

    public string Author { get; set; }

    public DateTime? Created { get; set; }

    public DateTime? Updated { get; set; }

    public string Category { get; set; }
}